/* Generated by make-exo-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

#if 1
#ifdef __XFCONF_C__
#undef xfconf_init 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_init) xfconf_init __attribute((alias("IA__xfconf_init"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_shutdown 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_shutdown) xfconf_shutdown __attribute((alias("IA__xfconf_shutdown"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_named_struct_register 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_named_struct_register) xfconf_named_struct_register __attribute((alias("IA__xfconf_named_struct_register"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_array_free 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_array_free) xfconf_array_free __attribute((alias("IA__xfconf_array_free"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#endif
#endif
#if 1
#ifdef __XFCONF_ERRORS_C__
#undef xfconf_error_get_type 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_error_get_type) xfconf_error_get_type __attribute((alias("IA__xfconf_error_get_type"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_get_error_quark 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_get_error_quark) xfconf_get_error_quark __attribute((alias("IA__xfconf_get_error_quark"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#endif
#endif
#if 1
#ifdef __XFCONF_TYPES_C__
#undef xfconf_uint16_get_type 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_uint16_get_type) xfconf_uint16_get_type __attribute((alias("IA__xfconf_uint16_get_type"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_value_get_uint16 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_value_get_uint16) xfconf_g_value_get_uint16 __attribute((alias("IA__xfconf_g_value_get_uint16"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_value_set_uint16 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_value_set_uint16) xfconf_g_value_set_uint16 __attribute((alias("IA__xfconf_g_value_set_uint16"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_int16_get_type 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_int16_get_type) xfconf_int16_get_type __attribute((alias("IA__xfconf_int16_get_type"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_value_get_int16 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_value_get_int16) xfconf_g_value_get_int16 __attribute((alias("IA__xfconf_g_value_get_int16"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_value_set_int16 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_value_set_int16) xfconf_g_value_set_int16 __attribute((alias("IA__xfconf_g_value_set_int16"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#endif
#endif
#if 1
#ifdef __XFCONF_CHANNEL_C__
#undef xfconf_channel_get_type 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_type) xfconf_channel_get_type __attribute((alias("IA__xfconf_channel_get_type"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get) xfconf_channel_get __attribute((alias("IA__xfconf_channel_get"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_new 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_new) xfconf_channel_new __attribute((alias("IA__xfconf_channel_new"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_new_with_property_base 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_new_with_property_base) xfconf_channel_new_with_property_base __attribute((alias("IA__xfconf_channel_new_with_property_base"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_has_property 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_has_property) xfconf_channel_has_property __attribute((alias("IA__xfconf_channel_has_property"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_is_property_locked 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_is_property_locked) xfconf_channel_is_property_locked __attribute((alias("IA__xfconf_channel_is_property_locked"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_reset_property 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_reset_property) xfconf_channel_reset_property __attribute((alias("IA__xfconf_channel_reset_property"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_properties 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_properties) xfconf_channel_get_properties __attribute((alias("IA__xfconf_channel_get_properties"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_string 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_string) xfconf_channel_get_string __attribute((alias("IA__xfconf_channel_get_string"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_string 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_string) xfconf_channel_set_string __attribute((alias("IA__xfconf_channel_set_string"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_int 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_int) xfconf_channel_get_int __attribute((alias("IA__xfconf_channel_get_int"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_int 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_int) xfconf_channel_set_int __attribute((alias("IA__xfconf_channel_set_int"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_uint 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_uint) xfconf_channel_get_uint __attribute((alias("IA__xfconf_channel_get_uint"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_uint 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_uint) xfconf_channel_set_uint __attribute((alias("IA__xfconf_channel_set_uint"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_uint64 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_uint64) xfconf_channel_get_uint64 __attribute((alias("IA__xfconf_channel_get_uint64"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_uint64 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_uint64) xfconf_channel_set_uint64 __attribute((alias("IA__xfconf_channel_set_uint64"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_double 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_double) xfconf_channel_get_double __attribute((alias("IA__xfconf_channel_get_double"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_double 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_double) xfconf_channel_set_double __attribute((alias("IA__xfconf_channel_set_double"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_bool 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_bool) xfconf_channel_get_bool __attribute((alias("IA__xfconf_channel_get_bool"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_bool 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_bool) xfconf_channel_set_bool __attribute((alias("IA__xfconf_channel_set_bool"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_string_list 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_string_list) xfconf_channel_get_string_list __attribute((alias("IA__xfconf_channel_get_string_list"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_string_list 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_string_list) xfconf_channel_set_string_list __attribute((alias("IA__xfconf_channel_set_string_list"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_property 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_property) xfconf_channel_get_property __attribute((alias("IA__xfconf_channel_get_property"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_property 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_property) xfconf_channel_set_property __attribute((alias("IA__xfconf_channel_set_property"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_array 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_array) xfconf_channel_get_array __attribute((alias("IA__xfconf_channel_get_array"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_array_valist 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_array_valist) xfconf_channel_get_array_valist __attribute((alias("IA__xfconf_channel_get_array_valist"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_arrayv 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_arrayv) xfconf_channel_get_arrayv __attribute((alias("IA__xfconf_channel_get_arrayv"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_array 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_array) xfconf_channel_set_array __attribute((alias("IA__xfconf_channel_set_array"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_array_valist 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_array_valist) xfconf_channel_set_array_valist __attribute((alias("IA__xfconf_channel_set_array_valist"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_arrayv 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_arrayv) xfconf_channel_set_arrayv __attribute((alias("IA__xfconf_channel_set_arrayv"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_named_struct 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_named_struct) xfconf_channel_get_named_struct __attribute((alias("IA__xfconf_channel_get_named_struct"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_named_struct 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_named_struct) xfconf_channel_set_named_struct __attribute((alias("IA__xfconf_channel_set_named_struct"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_struct 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_struct) xfconf_channel_get_struct __attribute((alias("IA__xfconf_channel_get_struct"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_struct_valist 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_struct_valist) xfconf_channel_get_struct_valist __attribute((alias("IA__xfconf_channel_get_struct_valist"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_get_structv 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_get_structv) xfconf_channel_get_structv __attribute((alias("IA__xfconf_channel_get_structv"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_struct 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_struct) xfconf_channel_set_struct __attribute((alias("IA__xfconf_channel_set_struct"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_struct_valist 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_struct_valist) xfconf_channel_set_struct_valist __attribute((alias("IA__xfconf_channel_set_struct_valist"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_channel_set_structv 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_channel_set_structv) xfconf_channel_set_structv __attribute((alias("IA__xfconf_channel_set_structv"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_list_channels 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_list_channels) xfconf_list_channels __attribute((alias("IA__xfconf_list_channels"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#endif
#endif
#if 1
#ifdef __XFCONF_BINDING_C__
#undef xfconf_g_property_bind 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_property_bind) xfconf_g_property_bind __attribute((alias("IA__xfconf_g_property_bind"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_property_unbind 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_property_unbind) xfconf_g_property_unbind __attribute((alias("IA__xfconf_g_property_unbind"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_property_unbind_by_property 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_property_unbind_by_property) xfconf_g_property_unbind_by_property __attribute((alias("IA__xfconf_g_property_unbind_by_property"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_property_unbind_all 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_property_unbind_all) xfconf_g_property_unbind_all __attribute((alias("IA__xfconf_g_property_unbind_all"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_property_bind_gdkcolor 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_property_bind_gdkcolor) xfconf_g_property_bind_gdkcolor __attribute((alias("IA__xfconf_g_property_bind_gdkcolor"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#undef xfconf_g_property_bind_gdkrgba 
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
extern __typeof (xfconf_g_property_bind_gdkrgba) xfconf_g_property_bind_gdkrgba __attribute((alias("IA__xfconf_g_property_bind_gdkrgba"), visibility("default")));
G_GNUC_END_IGNORE_DEPRECATIONS

#endif
#endif

#endif /* HAVE_GNUC_VISIBILITY */
